/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Sun Apr 02 01:42:40 2017. */

#include "timestamp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t google_protobuf_Timestamp_fields[3] = {
    PB_FIELD(  1, INT64   , SINGULAR, STATIC  , FIRST, google_protobuf_Timestamp, seconds, seconds, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, google_protobuf_Timestamp, nanos, seconds, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
